version: '3'

services:
    caliper:
        container_name: caliper
        working_dir: /hyperledger/caliper/workspace
        image: hyperledger/caliper:0.4.2
        command: launch manager
        network_mode: host
        environment:
        - CALIPER_BIND_SUT=besu:latest
        - CALIPER_BENCHCONFIG=benchmarks/scenario/registry/config.yaml
        - CALIPER_NETWORKCONFIG=networks/networkconfig.json
        - CALIPER-FLOW-SKIP-INSTALL=true
        volumes:
        - .:/hyperledger/caliper/workspace