test:
    name: poolmarket
    description: To benchmark the network transactions.
    workers:
        type: local
        number: 40
    rounds:
    -   label: submit offers
        description: Sumitting an offer to market with given account and info.
        txNumber: 40
        rateControl:
            type: fixed-rate
            opts:
                tps: 40
        workload:
            module: benchmarks/scenario/market/submitOffer.js
            arguments:
                numberOfAccounts: 40
                blockNumber: 1
                offerAmount: 300
                offerPrice: 45
                bidAmount: 250
                bidPrice: 40
    -   label: submit bids
        description: Sumitting a bid to market with given account and info.
        txNumber: 40
        rateControl:
            type: fixed-rate
            opts:
                tps: 40
        workload:
            module: benchmarks/scenario/market/submitBid.js
            arguments:
                numberOfAccounts: 40
                blockNumber: 1
                offerAmount: 300
                offerPrice: 45
                bidAmount: 250
                bidPrice: 40
