simpleArgs: &simple-args
  numberOfAccounts: 10
  blockNumber: 1
  offerAmount: 300
  offerPrice: 45
  bidAmount: 250
  bidPrice: 40

test:
  name: poolmarket
  description: >-
    To benchmark the network transactions.
  workers:
    type: local
    number: 10
  rounds:
    - label: submit offers
      description: Sumitting an offer to market with given account and info.
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/poolmarket/submitOffer.js
        arguments:
          << : *simple-args

    - label: submit bids
      description: Sumitting a bid to market with given account and info.
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/poolmarket/submitBid.js
        arguments:
          << : *simple-args