simpleArgs: &simple-args
  moneyToTransfer: &money-to-transfer 0
  numberOfAccounts: 50

test:
  name: erc20
  description: >-
    To benchmark the network transactions.
  workers:
    type: local
    number: 5
  rounds:
    - label: 200 txns with 10-100tps
      description: Transfering erc20 token between accounts.
      txNumber: 200
      rateControl:
        type: linear-rate
        opts:
          startingTps: 10
          finishingTps: 100
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          << : *simple-args
          money: *money-to-transfer
    - label: 50 txns with 10tps
      description: Transfering erc20 token between accounts.
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          << : *simple-args
          money: *money-to-transfer
